# Generated by Django 3.2.4 on 2022-04-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumb',
            new_name='thumbnail',
        ),
    ]
